### ISSUE TITLE
The cutscenes dialogue has no sound.

### ISSUE THREAD

**Issue by MisterBooks** [bearsdotzone/tss-audio-data#1]
I try to put the dialogue in the thai dub version of Star Wars EP3 film into the game cutscene.
by editing the dialogue to match the original and save it as an ogg file

I've used your tool to convert the file and replace the original file
At the scene I modded, the dialogue sound disappeared.

Am I missing something?
what should i do?

**Comment by bearsdotzone** [comment]
release v2 creates an appropriately tagged audio data file from the source ogg
